#pragma once

#include <cstdint>

enum SwitchConstants : int8_t {
	ACK                           = -128,
	BLUETOOTH_MANUAL_PAIRING      = 1,
	BUTTON_REPORT                 = 63,
	CAPTURE_BIT                   = 32,
	CONTROLLER_STATE              = 0,
	DOWN_BIT                      = 1,
	FULL_A_BIT                    = 8,
	FULL_BUTTON_REPORT            = 48,
	FULL_B_BIT                    = 4,
	FULL_CAPTURE_BIT              = 32,
	FULL_DOWN_BIT                 = 1,
	FULL_HOME_BIT                 = 16,
	FULL_LEFT_BIT                 = 8,
	FULL_LEFT_STICK_BIT           = 8,
	FULL_L_R_BIT                  = 64,
	FULL_MINUS_BIT                = 1,
	FULL_PLUS_BIT                 = 2,
	FULL_RIGHT_BIT                = 4,
	FULL_RIGHT_STICK_BIT          = 4,
	FULL_SL_BIT                   = 32,
	FULL_SR_BIT                   = 16,
	FULL_UP_BIT                   = 2,
	FULL_X_BIT                    = 2,
	FULL_Y_BIT                    = 1,
	FULL_ZL_ZR_BIT                = -128,
	HOME_BIT                      = 16,
	LEFT_BIT                      = 4,
	LEFT_STICK_BIT                = 4,
	L_R_BIT                       = 64,
	MINUS_BIT                     = 1,
	PLUS_BIT                      = 2,
	REQUEST_AXIS_SENSOR           = 64,
	REQUEST_DEVICE_INFO           = 2,
	REQUEST_INPUT_REPORT_MODE     = 3,
	REQUEST_RUMBLE                = 16,
	REQUEST_RUMBLE_AND_SUBCOMMAND = 1,
	REQUEST_SET_PLAYER_LIGHTS     = 48,
	REQUEST_SET_SHIPMENT          = 8,
	REQUEST_SPI_FLASH_READ        = 16,
	REQUEST_TRIGGER_BUTTONS       = 4,
	REQUEST_VIBRATION             = 72,
	RIGHT_BIT                     = 2,
	RIGHT_STICK_BIT               = 8,
	SL_BIT                        = 16,
	SR_BIT                        = 32,
	SUBCOMMAND_REPLY_REPORT       = 33,
	UP_BIT                        = 8,
	ZL_ZR_BIT                     = -128,
};